version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "3008:3001"
    environment:
      - ADMIN_TOKEN=XXXXXX
    volumes:
      - ./server/data:/app/data
    restart: always

  client:
    build: ./client
    ports:
      - "8090:80"
    depends_on:
      - server
    restart: always
